version: "3.9"

services:
  proxy:
    image: tailscale/tailscale:stable
    privileged: true
    ports:
      - "1055:1055/tcp"
      - "1055:1055/udp"
    environment:
      TS_AUTHKEY: "${TS_AUTHKEY}"
      TS_SOCKS5_SERVER: ":1055"
      # TS_OUTBOUND_HTTP_PROXY_LISTEN: ":${TS_HTTP_PORT}"
      TS_EXTRA_ARGS: "--exit-node=${TS_EXITNODE} --exit-node-allow-lan-access --shields-up"
    volumes:
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      - NET_RAW
    tmpfs:
      - /tmp
    restart: unless-stopped

networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 1280 # tailscale/tailscale#3877
